version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8070:80"
    depends_on:
      - api
